# Generated by Django 5.0.4 on 2024-04-07 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemName", models.CharField(max_length=200)),
                ("unitPrice", models.FloatField(verbose_name="Unit price")),
                ("unitWeight", models.FloatField(verbose_name="Unit weight")),
            ],
        ),
        migrations.CreateModel(
            name="Dispose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disposeDate", models.DateField(verbose_name="disposal date")),
                ("numItem", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dispose.menuitem",
                    ),
                ),
            ],
        ),
    ]
